apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  ports:
    - port: 8080
      name: http
  type: LoadBalancer
  selector:
    app: labeled-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1 # kpt-set: ${app-replicas}
  selector:
    matchLabels:
      app: labeled-app
  template:
    metadata:
      labels:
        app: labeled-app
    spec:
      containers:
        - name: app
          image: app-image-name
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

          env:
            - name: DATABASE_URL
              value: postgres://pgapp:example@postgres.default.svc.cluster.local:5432/pgapp
