apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  ports:
  - port: 8080
    name: http
  type: LoadBalancer
  selector:
    app: labeled-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: labeled-app
  template:
    metadata:
      labels:
        app: labeled-app
    spec:
      containers:
      - name: app
        image: app-image-name
        imagePullPolicy: Never
        ports:
          - containerPort: 8080
